substitutions:
  friendly_name: "Device Name"
  name: device-name
  board: nodemcu-32s
  
  ip: 192.168.x.x
  gateway: !secret gateway
  subnet: !secret subnet

  password: !secret password
  encryption_key: !secret encryption_key  
  
  wifi_ssid: !secret wifi_ssid
  wifi_pswd: !secret wifi_password

#########################################

packages:
  remote_package:
    url: https://github.com/topaniot/ESPHome-Templates
    ref: main
    refresh: 30s
    files:
      - packages/default_config.yaml
      - packages/default_sensors.yaml
      - packages/esp32_specific.yaml
      - packages/wifi_static.yaml
      - packages/bluetooth_proxy.yaml
