substitutions:
  friendly_name: "HLK LD2410"
  name: hlk-ld2410
  board: nodemcu-32s
  
  password: !secret password
  encryption_key: !secret encryption_key  
  
  wifi_ssid: !secret wifi_ssid
  wifi_pswd: !secret wifi_password
  
#########################################

packages:
  remote_package:
    url: !secret github_url
    ref: main
    refresh: !secret refresh_time
    files:
      - packages/default_config.yaml
      - packages/default_sensors.yaml
      - packages/esp32_specific.yaml
      - packages/wifi_dhcp.yaml
      - packages/bluetooth_proxy.yaml
      - packages/compile_limit.yaml

# HLK LD2410 Sensor
uart:
  tx_pin: 1
  rx_pin: 3
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  timeout: 5s
  max_move_distance : 6m
  max_still_distance: 6m

  g0_still_threshold: 0
  g1_still_threshold: 0
  g2_still_threshold: 40
  g3_still_threshold: 40
  g4_still_threshold: 40
  g5_still_threshold: 40
  g6_still_threshold: 15
  g7_still_threshold: 15
  g8_still_threshold: 15
   
  
  g0_move_threshold: 50
  g1_move_threshold: 50 
  g2_move_threshold: 40
  g3_move_threshold: 40
  g4_move_threshold: 40
  g5_move_threshold: 40
  g6_move_threshold: 30
  g7_move_threshold: 30
  g8_move_threshold: 30

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

sensor:
  - platform: ld2410
    moving_distance:
      name : Moving Distance
    still_distance:
      name: Still Distance
    moving_energy:
      name: Move Energy
    still_energy:
      name: Still Energy
    detection_distance:
      name: Detection Distance
