substitutions:
  friendly_name: "Device Name"
  name: device-name
  compile_limit: "4"
  
  ip: 192.168.0.0
  ip_com: 192.168.0.0
  gateway: !secret gateway
  subnet: !secret subnet

  board: esp01_1m
  password: !secret password
  encryption_key: !secret encryption_key  
  
  wifi_ssid: !secret wifi_ssid
  wifi_pswd: !secret wifi_password

  # Optional
  # wifi_ssid2: !secret wifi_ssid2
  # wifi_pswd2: !secret wifi_password2
  
  # Define I2C Pins  
  i2c_sda: "1"
  i2c_scl: "3"

#########################################

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  compile_process_limit: ${compile_limit}

esp8266:
  board: ${board}

logger:
captive_portal:

api:
  reboot_timeout: 5min
  encryption:
    key: ${encryption_key}

ota:
  password: ${password}

wifi:
  # First SSID
  networks:
  - ssid: ${wifi_ssid}
    password: ${wifi_pswd}

  # Second SSID
  # - ssid: ${wifi_ssid2}
  #   password: ${wifi_pswd2}
  
  # Manual IP
  manual_ip:
    static_ip: ${ip}
    gateway: ${gateway}
    subnet: ${subnet}
  use_address: ${ip_com}
  # AP for Fallback
  ap:
    ssid: "${friendly_name}"
    password: ${password}

# Enable Web Server
web_server:
  port: 80
  auth:
    username: ${name}
    password: ${password}

# Setup I2C
i2c:
  sda: ${i2c_sda}
  scl: ${i2c_scl}  
  scan: true
  id: bus_a

button:
  # Restart Button
  - platform: restart
    name: "Restart"

text_sensor:    
  # WiFi Info
  - platform: wifi_info
    ip_address:
      name: "IP"
      icon: "mdi:ip-network"
      disabled_by_default: true
    ssid:
      name: "SSID"
      icon: "mdi:wifi-strength-4"
      disabled_by_default: true

sensor:
  # HTU21
  - platform: htu21d
    temperature:
      name: "HTU21 Temperature"
    humidity:
      name: "HTU21 Humidity"
    update_interval: 60s

  # WiFi Signal
  - platform: wifi_signal
    name: "RSSI"
    update_interval: 120s
    filters:
      - lambda: |-
          float VALUE = -20.0;
          if (x <= VALUE) return x;
          else return {};
    
  # VCC Voltage
  - platform: adc
    pin: VCC
    name: "VCC Voltage"
    disabled_by_default: true
    

# Device Specific Config shelly1
output:
  - platform: gpio
    pin: GPIO4
    id: shelly_1_relay

light:
  - platform: binary
    name: ""
    output: shelly_1_relay
    id: lightid

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Input"
    on_state:
      then:
        - light.toggle: lightid
    internal: true
    id: switchid
