substitutions:
  friendly_name: "Device Name"
  name: device-name
  icon: mdi:switch
  
  password: !secret password
  encryption_key: !secret encryption_key  
  
  wifi_ssid: !secret wifi_ssid
  wifi_pswd: !secret wifi_password


  # Additional packages
  
  # Second SSID
  # wifi_ssid2: !secret wifi_ssid2
  # wifi_pswd2: !secret wifi_password2
  
  # Static IP
  # ip: 192.168.x.x
  # ip_com: 192.168.x.x
  # gateway: !secret gateway
  # subnet: !secret subnet
  
  # HTU21 Sensor
  # i2c_sda: "1"
  # i2c_scl: "3"
  # htu21_update_interval: 60s
  
  
  
#########################################

packages:
  remote_package:
    url: https://github.com/topaniot/ESPHome-Templates
    ref: main
    refresh: 300s
    files: [
      packages/sonoff_basic_switch.yaml,
      packages/wifi_dhcp.yaml,
      packages/default_config.yaml,
      packages/default_sensors.yaml,
      packages/compile_limit.yaml]

