# Substitutions needed
# board: nodemcu-32s

esp32:
  board: ${board}
  framework:
    type: esp-idf
    sdkconfig_options:
      CONFIG_BT_RESERVE_DRAM_ONLY: "y"
      # Enable WiFi/BLE coexistence
      CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE: "y"

bluetooth_proxy:
  active: true

esp32_ble_tracker:
  scan_parameters:
    active: true
    interval: 150ms
    window: 120ms
  on_ble_advertise:
    then:
      - binary_sensor.template.publish:
          id: ble_activity_monitor
          state: ON

binary_sensor:
  - platform: template
    id: ble_activity_monitor
    name: "BLE Activity Watchdog"
    internal: false
    disabled_by_default: true
    filters:
      - delayed_off: 5min
    on_release:
      then:
        - logger.log: "No BLE traffic. Triggering restart button..."
        - button.press: restart_button
