esphome:
  name: ${name}
  friendly_name: ${friendly_name}

logger:
captive_portal:

api:
  reboot_timeout: 5min
  encryption:
    key: ${encryption_key}

ota:
  password: ${password}

web_server:
  port: 80
  auth:
    username: ${name}
    password: ${password}

button:
  # Restart Button
  - platform: restart
    name: "Restart"
