### Default config for devices
# Substitutions needed
#
# substitutions:
#   friendly_name: "Boxe"
#   name: boxe
# 
#   password: !secret password
#   encryption_key: !secret encryption_key  


esphome:
  name: ${name}
  friendly_name: ${friendly_name}

logger:
captive_portal:

wifi:
  ap:
    ssid: ${friendly_name}
    password: ${password}

api:
  encryption:
    key: ${encryption_key}
  reboot_timeout: 0s

ota:
  platform: esphome
  password: ${password}

web_server:
  port: 80
  auth:
    username: ${name}
    password: ${password}

button:
  # Restart Button
  - platform: restart
    name: "Restart"
    id: restart_button
