### Package for DS18B20 
# substitutions:
#   ds18b20_adress: "0x2801144ef2caaa28"
#   ds18b20_pin: GPIO0


one_wire:
  - platform: gpio
    pin: ${ds18b20_pin}
  
sensor:  
  - platform: dallas_temp
    id: ds18b20_sensor
    address: ${ds18b20_adress}
    name: "DS18B20 Temperature"
