### Lite config for devices
# Substitutions needed
#
# substitutions:
#   friendly_name: "Boxe"
#   name: boxe
# 
#   password: !secret password
#   encryption_key: !secret encryption_key  


esphome:
  name: ${name}
  friendly_name: ${friendly_name}

logger:

api:
  encryption:
    key: ${encryption_key}
  reboot_timeout: 1h

ota:
  platform: esphome
  password: ${password}

button:
  # Restart Button
  - platform: restart
    name: "Restart"
    id: restart_button
