### Device Specific Config Shelly 1 as switch
# Substitutions needed
#
# substitutions:
#   icon: mdi:switch
 
esp8266:
  board: esp01_1m

# Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO5
    name: "Input"
    disabled_by_default: true
    on_state:
      - switch.toggle: relay

# Relay
switch:
  - platform: gpio
    name: ""
    pin: GPIO4
    id: relay
    icon: ${icon}
