# Shelly 1 PM
# Substitutions needed
#
# substitutions:
#   icon: "mdi:radiator"
#   max_temp: "70.0"
#   b_constant: 3350
#   reference_temperature: 298.15K
#   reference_resistance: 10kOhm
#   resistor: 3.3kOhm
  
  
esp8266:
  board: esp01_1m
  
  
# Device Specific Config
  - platform: hlw8012
    cf_pin: GPIO05
    cf1_pin: GPIO13 # not used because it is not available on the 1PM but it is needed to compile
    sel_pin: GPIO14 # not used because it is not available on the 1PM but it is needed to compile
    power:
      name: "Power"
      unit_of_measurement: W
      id: "shelly1pm_power"
      device_class: power
      state_class: measurement
      accuracy_decimals: 0
      filters:
      # Map from sensor -> measured value
      - calibrate_linear:
          - 0.0 -> 1.0
          - 110.33186 -> 20.62
          - 131.01909 -> 24.32
          - 341.33920 -> 62.08
          - 5561.41553 -> 1000.0
          - 2975.51221 -> 535.7
          - 9612.66309 -> 1720.0
          - 14891.35352 -> 2679.0
      # Make everything below 2W appear as just 0W.
      - lambda: if (x < 2) return 0; else return x;
    update_interval: 10s

  - platform: total_daily_energy
    name: "Daily Energy"
    power_id: "shelly1pm_power"
    device_class: energy
    state_class: total_increasing
    filters:
      - multiply: 0.001
    unit_of_measurement: kWh

  - platform: ntc
    sensor: temp_resistance_reading
    name: "Analog Temperature"
    id: device_internal_temp
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    device_class: temperature
    calibration:
      b_constant: ${b_constant}
      reference_temperature: ${reference_temperature}
      reference_resistance: ${reference_resistance}

  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: ${resistor}
    
  - platform: adc
    id: temp_analog_reading
    pin: A0
    
  output:
  - platform: esp8266_pwm
    id: state_led
    pin:
      number: GPIO00
      inverted: true
      
 # Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO4
    filters:
      - delayed_on_off: 50ms
    name: "Input"
    on_press:
      then:
        - switch.toggle: shelly_relay
    disabled_by_default: true
    id: switchid

# Sonoff Relay
switch:
  - platform: gpio
    name: ""
    pin: GPIO15
    id: shelly_relay
    restore_mode: ALWAYS_OFF
    icon: "${icon}"

# Overheat Protection
interval:
  - interval: 500ms
    then:
      if:
        condition:
          and:
            - sensor.in_range:
                id: device_internal_temp
                above: ${max_temp}
            - switch.is_on: shelly_relay
        then:
          - switch.turn_off: shelly_relay
