### Device Specific Config Package

esp8266:
  board: esp01_1m
  restore_from_flash: true
  
# Sonoff Status LED
status_led:
  pin:
    number: GPIO13
    inverted: yes

# Sonoff Relay
output:
  - platform: gpio
    pin: GPIO12
    id: sonoff_relay

light:
  - platform: binary
    name: ""
    output: sonoff_relay
    id: lightid

# Sonoff Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    disabled_by_default: true
    on_press:
      - light.toggle: lightid
