# Sonoff T3 template

esp8266:
  board: esp01_1m
  
output:
  - platform: gpio
    pin: GPIO12
    id: relay_1
    
  - platform: gpio
    pin: GPIO5
    id: relay_2
    
  - platform: gpio
    pin: GPIO4
    id: relay_3

  # BLUE LED
  - platform: esp8266_pwm
    id: blue_led
    pin: GPIO13
    inverted: true

light:
    
  - platform: binary
    name: ""
    id: light_1
    output: relay_1
    
  - platform: binary
    name: "2"
    id: light_2
    output: relay_2
    
  - platform: binary
    name: "3"
    id: light_3
    output: relay_3
    
  # BLUE LED
  - platform: monochromatic
    name: "Blue LED"
    output: blue_led
    internal: true
    id: blue_led_light
  
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Touchpad 1"
    on_press:
      - light.toggle: light_1
  - platform: gpio
    pin:
      number: GPIO9
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Touchpad 2"
    on_press:
      - light.toggle: light_2
  - platform: gpio
    pin:
      number: GPIO10
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Touchpad 3"
    on_press:
      - light.toggle: light_3
  - platform: status
    name: "Status"
