### Device Specific Config Package
# Substitutions needed
#
# substitutions:
#   icon: mdi:switch

esp8266:
  board: esp01_1m
  restore_from_flash: true

# Sonoff Status LED
status_led:
  pin:
    number: GPIO13
    inverted: yes

# Sonoff Relay
switch:
  - platform: gpio
    name: ""
    pin: GPIO12
    id: relay
    icon: ${icon}
    restore_mode: RESTORE_DEFAULT_OFF

# Sonoff Button
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Button"
    disabled_by_default: true
    on_press:
      - switch.toggle: relay
    on_click:
      min_length: 10s
      max_length: 30s
      then:
        - button.press: restart_button
      
