### TIOT Module as switch
# Substitutions needed
# substitutions:
#   icon: mdi:switch

esp8266:
  board: esp01_1m
  restore_from_flash: true

# TIOT Buttons
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO12
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Input 1"
    disabled_by_default: true
    on_state:
      - switch.toggle: relay
  - platform: gpio
    pin:
      number: GPIO13
      mode:
        input: true
        pullup: true
      inverted: true
    name: "Input 2"
    disabled_by_default: true

# TIOT Relay
switch:
  - platform: gpio
    name: ""
    pin: GPIO4
    id: relay
    icon: ${icon}
